### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by chadhahn** [Mashape/homebrew-kong#20]
Trying to install w/ "brew install kong"

Error: SHA256 mismatch
Expected: 7c604bafd0f3600ff2b7225ba69d60d3504fabb1c332a6b371b47d14019d973e
Actual: b0320d1c519125713926963e59fbb3cf8969ecbb0d5fa5bfbd87c179c22290d2

**Comment by DoctorU** [comment]
+1: 

    $ brew install kong
    ==> Installing kong from mashape/kong
    ==> Downloading https://github.com/Mashape/kong/archive/0.6.0.tar.gz
    ==> Downloading from https://codeload.github.com/Mashape/kong/tar.gz/0.6.0
    ######################################################################## 100.0%
    Error: SHA256 mismatch
    Expected: 7c604bafd0f3600ff2b7225ba69d60d3504fabb1c332a6b371b47d14019d973e
    Actual: b0320d1c519125713926963e59fbb3cf8969ecbb0d5fa5bfbd87c179c22290d2
    Archive: /Library/Caches/Homebrew/kong-0.6.0.tar.gz
    To retry an incomplete download, remove the file above.

**Comment by thibaultCha** [comment]
Indeed, the 0.6.0 tag was moved on the Kong repository without me being informed about it. I just updated it so a `brew update && brew install` should work now.

**Comment by seanbrowntruera** [comment]
```Error: kong: SHA256 mismatch
Expected: 848452e07cc5d4bff73f3d4c0ac12dcb63ede89029b5e9dec5eab1fe28fbe5c8
  Actual: 9397eb077960af5205f31b5a85025bc5262aee47054b4a797e569553ba3d8371
    File: /Library/Caches/Homebrew/downloads/8c26686f439ddceab9e9adaebceacf2b41b9a360a9c5d531755d9e9a05506837--kong-build-tools-4.33.22.tar.gz
To retry an incomplete download, remove the file above.```

I ran ```brew update && brew install``` but I'm still getting this error. I'm running this on an M1

**Comment by mehuled** [comment]
facing the same issue for kong:2.8.2

**Comment by saketbairoliya2** [comment]
This worked out for me: 

cd /usr/local/Homebrew/Library/Taps/kong/homebrew-kong
git checkout 28c324f # checkout release 2.8.1
brew install kong
